---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "cosent"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Consent Management"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see org1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  mychannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      peer0.airport.example.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.airport.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.ccd.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.ccd.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.users.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.users.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - chainv1_3:v0

#
# list of participating organizations in this network
#
organizations:
  airport:
    mspid: airport

    peers:
      - peer0.airport.example.com
      - peer1.airport.example.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-airport

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: crypto-config/peerOrganizations/airport.example.com/users/Admin@airport.example.com/msp/keystore/38af105ab4697cba4ebcead7fd068eae977eb0e10081863204851462e241c121_sk
    signedCert:
      path: crypto-config/peerOrganizations/airport.example.com/users/Admin@airport.example.com/msp/signcerts/Admin@airport.example.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  ccd:
    mspid: ccd
    peers:
      - peer0.ccd.example.com
      - peer1.ccd.example.com
    certificateAuthorities:
      - ca-ccd
    adminPrivateKey:
      path: crypto-config/peerOrganizations/ccd.example.com/users/Admin@ccd.example.com/msp/keystore/a4c2b2b57b65cfe9e23df5df9d9f85a7e8769d637c087a347510673f83f39176_sk
    signedCert:
      path: crypto-config/peerOrganizations/ccd.example.com/users/Admin@ccd.example.com/msp/signcerts/Admin@ccd.example.com-cert.pem

  users:
    mspid: users
    peers:
      - peer0.users.example.com
      - peer1.users.example.com
    certificateAuthorities:
      - ca-users
    adminPrivateKey:
      path: crypto-config/peerOrganizations/users.example.com/users/Admin@users.example.com/msp/keystore/cd93b2e6bec6a8ddcc1fd50df1a2adf9a9579f0f547de21d689a06c404ae5202_sk
    signedCert:
      path: crypto-config/peerOrganizations/users.example.com/users/Admin@users.example.com/msp/signcerts/Admin@users.example.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.example.com

    tlsCACerts:
      path: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.airport.example.com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.airport.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/airport.example.com/peers/peer0.airport.example.com/tls/ca.crt

  peer1.airport.example.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.airport.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/airport.example.com/peers/peer1.airport.example.com/tls/ca.crt

  peer0.ccd.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.ccd.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/ccd.example.com/peers/peer0.ccd.example.com/tls/ca.crt

  peer1.ccd.example.com:
    url: grpcs://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer1.ccd.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/ccd.example.com/peers/peer1.ccd.example.com/tls/ca.crt

  peer0.users.example.com:
    url: grpcs://localhost:11051
    grpcOptions:
      ssl-target-name-override: peer0.users.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/users.example.com/peers/peer0.users.example.com/tls/ca.crt

  peer1.users.example.com:
    url: grpcs://localhost:12051
    grpcOptions:
      ssl-target-name-override: peer1.users.example.com
    tlsCACerts:
      path: crypto-config/peerOrganizations/users.example.com/peers/peer1.users.example.com/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-airport:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/airport.example.com/ca/ca.airport.example.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-airport

  ca-ccd:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/ccd.example.com/ca/ca.ccd.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-ccd

  ca-users:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: crypto-config/peerOrganizations/users.example.com/ca/ca.users.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca-users